name: 'README.md' build

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 */6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout current repository to 'main' branch
        uses: actions/checkout@v1

      - name: Setup Node.js 13.x
        uses: actions/setup-node@v1
        with:
          node-version: '13.x'

      - name: Cache dependencies and build outputs to improve workflow execution time
        uses: actions/cache@v1
        with:
          path: node_modules
          key: ${{ runner.os }}-js-${{ hashFiles('package-lock.json') }}

      - name: Install dependencies
        run: npm install

      - name: Generate 'README.md' file
        run: node index.js

      - name: Commit and push new 'README.md' to the repository
        uses: warcaith/publish-to-github-action@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}